### ISSUE TITLE
Licensing Type

### ISSUE THREAD

**Issue by jacobalanb9** [ahegazy/aes#2]
I am in a group of engineers at Brigham Young University. The Georgia Tech Research Institute has asked us to select an open source cryptographic core and try to identify security vulnerabilities. We are impressed with the core that has been designed and are considering using it is the core to perform our study on, but we are unaware of what Licensing exists for it. If there isn't any, can it be licensed as MIT or a similar license that would not require GTRI to publish their modifications if this core is selected?

**Comment by ahegazy** [comment]
Hello @jacobalanb9,
We didn't really think of licensing it, but sure MIT looks good.
I have added the license file to the repository.
I would appreciated if you kept me updated with your results if you choose.

Regards.

**Comment by ahegazy** [comment]
Hello @jacobalanb9,
We didn't really think of licensing it, but sure MIT looks good.
I have added the license file to the repository.
I would appreciated if you kept me updated with your results if you choose this core.

Regards.

**Comment by jacobalanb9** [comment]
Hi @ahegazy,
Thank you so much for adding the MIT license file! We really appreciate it! We are almost certain that we would like to use your core for our study. If we do so, we will let you know what we find out!
