### ISSUE TITLE
Initialization Vectors

### ISSUE THREAD

**Issue by jacobalanb9** [ahegazy/aes#4]
Hi @ahegazy,

When you have a moment, could you let me know where the aes initialization vectors are as well as the counter? We thought we found it under AddRoundKey.v, but we are almost certain that this is not the case.

Thanks!

Jacob

**Comment by ahegazy** [comment]
Hi @jacobalanb9,
I am a little rusty on this project tbh.
As far as I can remember, this was a very rudimentary implementation as a course project during collage, I don't think I used IVs, only state & key generation for each round.
Regarding the counters, you mean the counters for key generation and rounds right, you'll find a register called keyNum generated at the top level FSM used for key generation for each round, all rounds uses the same blocks (some rounds might disable some stages) so the inputs are sent to each block and blocks are enabled/disabled accordingly using this FSM. 

Regards,
Hegazy.

**Comment by jacobalanb9** [comment]
Okay cool! Thanks for taking the time to clarify this!
